config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  # --------------
  # AUTHENTICATION
  # --------------

  match  '/auth/github/callback'        => 'sessions#create', via: [:get, :post]
  delete '/signout'                     => 'sessions#destroy', as: :signout
  get    '/auth/failure'                => 'sessions#failure'

  match  '/auth/stackexchange/callback' => 'users#connect_stackoverflow', via: [:get, :post]

  resources :resources, only: [:new, :create] do
    collection { get :bookmarklet }
  end

  resources :courses, shallow: true do
    collection { post :sort }

    resources :skills, shallow: true, except: [:index] do
      collection { post :sort }

      member { get :presentation }

      resources :resources, except: [:index, :show] do
        member do
          put 'like',    to: 'resources#upvote'
          put 'dislike', to: 'resources#downvote'
        end
      end

      resources :projects, shallow: true, except: [:index] do
        resources :project_completions, path: '/showcases', except: [:index] do
          member { get :screenshot }
          member { put :approve }
        end
      end
    end
  end

  resources :project_completions, path: '/showcases', only: [:index]

  resources :enrollments, only: [:index]

  get 'users/profile', as: :user_profile

  get 'stackoverflow/tags', as: :stackoverflow_tags

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/concerns/skill/dag_methods.rb
module ::Concerns::Skill::DagMethods
  extend ActiveSupport::Concern

  def dag_label
    position.to_s + ':' + primary_language.abbrev
  end

  def dag_class
    [
      primary_language.abbrev.downcase
    ].join ' '
  end
end

app/models/concerns/skill/github_api_methods.rb
module ::Concerns::Skill::GithubApiMethods
  extend ActiveSupport::Concern

  # ---------
  # CALLBACKS
  # ---------

  included do
    after_save :update_gist
  end

  def update_gist
    return create_gist if self.gist_id.blank?

    self.creator.github_api.gists.edit(
      self.gist_id,
      files: files_for_gist
    )
  rescue
    false
  end

  def create_gist
    gist = self.creator.github_api.gists.create(
      description: self.title,
      public: false,
      files: files_for_gist
    )

    self.update_columns(gist_id: gist.id)
  rescue
    false
  end

  # --------------
  # SHARED METHODS
  # --------------

  def files_for_gist
    {
      "presentation.md" => {
        content: self.presentation
      }
    }
  end

  # ------------------
  # VIRTUAL ATTRIBUTES
  # ------------------

  def gist_url
    create_gist if self.gist_id.blank?
    "https://gist.github.com/#{self.gist_id}"
  end

end

app/models/concerns/skill/validations.rb
module ::Concerns::Skill::Validations
  extend ActiveSupport::Concern

  included do
    validates_presence_of :title, :primary_language, :course, :creator

    validates_uniqueness_of :title, scope: :course_id
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  include ::Concerns::Skill::DagMethods
  include ::Concerns::PaperTrail
  include ::Concerns::Skill::Validations
  include ::Concerns::Skill::GithubApiMethods

  belongs_to :course
  belongs_to :primary_language, class_name: 'Language'
  belongs_to :creator, class_name: 'User'

  has_many :skill_relationships, dependent: :destroy
  has_many :prereqs, through: :skill_relationships

  has_many :inverse_skill_relationships, class_name: 'SkillRelationship', foreign_key: 'prereq_id', dependent: :destroy
  has_many :inverse_prereqs, through: :inverse_skill_relationships, source: :skill

  has_many :resources
  has_many :projects
  has_one  :teaching_material

  acts_as_taggable

  acts_as_list scope: :course

  def related_stackoverflow_questions
    Rails.cache.fetch("related_stackoverflow_questions: {skill_id: #{self.title}, tags: #{self.tag_list}, version: 6}", expires_in: 1.day) do
      Array(
        RubyStackoverflow.similar(
          self.title,
          {
            tagged: self.tag_list.join(';'),
            pagesize: 10,
            sort: 'relevance',
            order: 'desc'
          }
        ).data
      ).map do |question|
        OpenStruct.new(JSON.parse(question.to_json))
      end
    end
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  load_and_authorize_resource :course
  load_and_authorize_resource :skill, through: :course, shallow: true, except: [:presentation, :sort]

  before_action :set_skill,  only: [:edit, :update, :destroy, :presentation]
  before_action :set_course, only: [:new, :create, :sort]

  def show
    @skill = Skill.includes(projects: [:creator, :criteria, :completions], resources: :creator).find(params[:id])
  end

  def new
    @skill = @course.skills.build
  end

  def edit
  end

  def create
    @skill = @course.skills.build skill_params.merge(creator_id: current_user.id)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
      else
        format.html { render :new }
      end
    end

  rescue ActiveRecord::RecordInvalid => e
    flash[:error] = e.message
    render :new
  end

  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
      else
        format.html { render :edit }
      end
    end

  rescue ActiveRecord::RecordInvalid => e
    flash[:error] = e.message
    render :edit
  end

  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Skill was successfully deleted.' }
    end
  end

  def sort
    authorize! :sort_skills_for, @course
    params[:skill].each_with_index do |id, index|
      Skill.find(id).update_attribute(:position, index+1)
    end
    render nothing: true
  end

  def presentation
    authorize! :read, @skill
    render text: @skill.presentation, layout: 'presentation'
  end

private

  def set_skill
    @skill = Skill.find(params[:id])
  end

  def set_course
    @course = Course.find(params[:course_id])
  end

  def skill_params
    params.require(:skill).permit(:title, :presentation, :primary_language_id, :tag_list, :read_only, prereq_ids: [])
  end
end

app/helpers/skills_helper.rb
module SkillsHelper

  def example_skill_slides
    %{<!-- EXAMPLE SLIDES -->

# First Slide

It's number one!

Note:

Make lots of funny jokes here, so people like you.

--

## Subslide 1

``` javascript
$('#example').show();
```

--

## Subslide 2
![This is how I explain computer problems to my cat. My cat usually seems happier than me.](http://imgs.xkcd.com/comics/computer_problems.png)

----

# Videos too!

--

## HTML5
<video class="stretch" data-autoplay controls src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"></video>

--

## YouTube
<iframe class="stretch" src="//www.youtube.com/embed/YE7VzlLtp-4?enablejsapi=1" frameborder="0" allowfullscreen></iframe>}
  end

end

app/views/skills/_form.html.slim
= simple_form_for [@course, @skill] do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.association :primary_language, collection: Language.order(:name)
    = f.input :tag_list, label: 'Stack Overflow tags'
    - other_skills = @skill.course.skills.where.not(id: f.object.id)
    - if other_skills.any?
      = f.association :prereqs, collection: other_skills, label: 'Prerequisites'
    - if @skill.projects.none?
      = f.input :read_only
    = f.input :presentation, label: 'Presentation (written in GitHub Flavored Markdown for RevealJS)', input_html: { value: f.object.presentation || example_skill_slides }

  .form-actions
    = f.button :submit

javascript:
  CodeMirror.fromTextArea(document.getElementById('skill_presentation'), {
    mode: 'markdown',
    theme: 'base16-light',
    lineNumbers: false,
    tabSize: 2,
    lineWrapping: true,
    extraKeys: {
      Tab: function(cm) {
        var spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
        cm.replaceSelection(spaces);
      }
    }
  });

  $('#skill_tag_list').selectize({
    delimiter: ',',
    persist: false,
    load: function(query, callback) {
      if (!query.length) return callback();
      $.ajax({
        url: '/stackoverflow/tags.json',
        type: 'GET',
        dataType: 'json',
        data: {
          query: query,
        },
        error: function() {
          callback();
        },
        success: function(response) {
          console.log(response)
          callback(response);
        }
      });
    }
  });

app/views/skills/_table.html.slim
- if skills.any?

  table#skills_table.table.table-striped
    tbody data-update-url=sort_course_skills_path(skills.first.course) class="#{'sortable' if can?(:sort_skills_for, skills.first.course)}"
      - skills.each do |skill|
        - special_class = skill_class(skill)
        = content_tag_for :tr, skill, class: special_class, title: special_class.gsub('_',' ').titleize do
          td= skill.position
          td.full= link_to skill.title, skill
          td
            - if can? :update, skill
              = link_to 'Edit', edit_skill_path(skill)
          td
            - if can? :destroy, skill
              = link_to 'Delete', skill, data: { confirm: "Are you sure you want to permanently delete the \"#{skill.title}\" skill?" }, method: :delete, class: 'text-danger'

  javascript:

    $('#skills_table').find('tr').tooltip({container: '#dag', placement: 'left'});

- else

  p No skills have been created yet.

app/views/skills/edit.html.slim
- breadcrumb :skill, @skill

h1 Editing skill

== render 'form'

app/views/skills/new.html.slim
- breadcrumb :new_course_skill, @skill.course

h1 New skill

== render 'form'

app/views/skills/show.html.slim
- breadcrumb :skill, @skill

- if can? :update, @skill
  = link_to 'Edit Skill', edit_skill_path(@skill), class: 'btn btn-primary btn-block'

- if user_signed_in? && !current_user.mentor? && current_user.project_completions.none?
  = render 'shared/alert', type: :notice, message: "Welcome to your first skill! Typically, you'll want to take a look at the slides first, then at the resources for extra help. When you're feeling pretty comfortable with the content, try one of the projects by adding a showcase. Then for the curious-minded, the related Stack Overflow questions will often address common sources of confusion surrounding the topic."

.row

  .col-sm-6

    h3
      => link_to 'Slides', presentation_skill_path(@skill), target: '_blank'
      = link_to @skill.gist_url do
        .glyphicon.glyphicon-comment.align-bottom
    iframe src=presentation_skill_path(@skill) width='100%' height='350px'

    h3
      ' Projects
      - if can? :create_project_for, @skill
        = link_to new_skill_project_path(@skill) do
          .glyphicon.glyphicon-plus-sign
    - if @skill.projects.any?
      - @skill.projects.each do |project|
        .well
          h4.block-tight-top
            => link_to project.title, project
            - if can? :update, project
              ' (#{link_to 'Edit', edit_project_path(project)})
            - if can? :destroy, project
              | (
              = link_to 'Delete', project, data: {confirm: "Are you sure you want to permanently delete the \"#{project.title}\" project?"}, method: :delete, class: 'text-danger'
              | )
          p= md_to_html project.description, project.creator
          h5 Criteria:
          ul.project_criteria
            - project.criteria.each do |criterion|
              li= md_to_html criterion.description, project.creator
          - if can? :create, ProjectCompletion
            - project_completion = ProjectCompletion.find_by(project_id: project.id, user_id: current_user.id)
            - if project_completion
              .row
                .col-xs-6= link_to 'Edit project submission', edit_project_completion_path(project_completion), class: 'btn btn-primary btn-block'
                .col-xs-6= link_to 'View project', project_completion_path(project_completion), class: 'btn btn-info btn-block'
            - else
              = link_to 'Submit project', new_project_project_completion_path(project), class: 'btn btn-primary btn-block'
    - else
      p No projects have been created yet.

  .col-sm-6

    h3
      ' Resources
      - if can? :create, Resource
        = link_to new_skill_resource_path(@skill) do
          .glyphicon.glyphicon-plus-sign
    == render 'resources/table', resources: @skill.resources

    h3 Related Stack Overflow Questions
    - if (questions = @skill.related_stackoverflow_questions).any?
      table.table.table-striped
        tbody
          - questions.each do |question|
            tr
              td.dontbreak
                => question.score
                span.glyphicon.glyphicon-thumbs-up
              td.full= link_to question.title.html_safe, question.link, target: '_blank'
              td= '✔' if question.is_answered
    - else
      p No related questions were found.