config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  # --------------
  # AUTHENTICATION
  # --------------

  match  '/auth/github/callback'        => 'sessions#create', via: [:get, :post]
  delete '/signout'                     => 'sessions#destroy', as: :signout
  get    '/auth/failure'                => 'sessions#failure'

  match  '/auth/stackexchange/callback' => 'users#connect_stackoverflow', via: [:get, :post]

  resources :resources, only: [:new, :create] do
    collection { get :bookmarklet }
  end

  resources :courses, shallow: true do
    collection { post :sort }

    resources :skills, shallow: true, except: [:index] do
      collection { post :sort }

      member { get :presentation }

      resources :resources, except: [:index, :show] do
        member do
          put 'like',    to: 'resources#upvote'
          put 'dislike', to: 'resources#downvote'
        end
      end

      resources :projects, shallow: true, except: [:index] do
        resources :project_completions, path: '/showcases', except: [:index] do
          member { get :screenshot }
          member { put :approve }
        end
      end
    end
  end

  resources :project_completions, path: '/showcases', only: [:index]

  resources :enrollments, only: [:index]

  get 'users/profile', as: :user_profile

  get 'stackoverflow/tags', as: :stackoverflow_tags

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/resources/_form.html.slim
= simple_form_for [@skill, @resource] do |f|
  = f.error_notification

  .form-inputs
    = f.input :title, input_html: { value: f.object.title || params[:title] }
    = f.input :url,   input_html: { value: f.object.url   || params[:url]   }, label: 'URL'
    - unless @resource.skill
      = f.association :skill, collection: @skills.order(:title).pluck(:title, :id)

  .form-actions
    = f.button :submit

app/views/resources/_table.html.slim
- if resources.any?

  - can_edit_any    = resources.any?{|resource| can? :update,  resource}
  - can_destroy_any = resources.any?{|resource| can? :destroy, resource}

  table#resources_table.table.table-striped
    tbody
      - resources.sort_by{|resource| [resource.rating, resource.created_at]}.reverse.each do |resource|
        tr
          td.dontbreak
            => resource.get_upvotes.count
            - if !can?(:vote_on, resource) || current_user.liked?(resource)
              span.glyphicon.glyphicon-thumbs-up>
            - else
              = link_to like_resource_path(resource), method: :put do
                span.glyphicon.glyphicon-thumbs-up
          td.dontbreak
            => resource.get_downvotes.count
            - if !can?(:vote_on, resource) || current_user.disliked?(resource)
              span.glyphicon.glyphicon-thumbs-down
            - else
              = link_to dislike_resource_path(resource), method: :put do
                span.glyphicon.glyphicon-thumbs-down
          td.full
            => link_to resource.title, resource.url, target: '_blank'
          - if can_edit_any
            td
              - if can? :update, resource
                = link_to 'Edit', edit_resource_path(resource)
          - if can_destroy_any
            td
              - if can? :destroy, resource
                = link_to 'Delete', resource, data: {confirm: "Are you sure you want to permanently delete the \"#{resource.title}\" resource?"}, method: :delete, class: 'text-danger'

- else

  p No resources have been added yet.

app/views/resources/edit.html.slim
- breadcrumb :resource, @resource

h1 Editing resource

== render 'form'

app/views/resources/new.html.slim
- if @resource.skill
  - breadcrumb :new_skill_resource, @resource.skill

h1 New resource

- if @resource.skill || (@course_id && (@skills = Skill.where(course_id: @course_id)).any?)
  == render 'form'
- elsif !@course_id
  = render 'shared/alert', type: :error, message: 'Course to save a resource for must be specified as a URL parameter.'
- elsif @skills.none?
  = render 'shared/alert', type: :error, message: 'Skills need to exist before resources can be saved.'