config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  # --------------
  # AUTHENTICATION
  # --------------

  match  '/auth/github/callback'        => 'sessions#create', via: [:get, :post]
  delete '/signout'                     => 'sessions#destroy', as: :signout
  get    '/auth/failure'                => 'sessions#failure'

  match  '/auth/stackexchange/callback' => 'users#connect_stackoverflow', via: [:get, :post]

  resources :resources, only: [:new, :create] do
    collection { get :bookmarklet }
  end

  resources :courses, shallow: true do
    collection { post :sort }

    resources :skills, shallow: true, except: [:index] do
      collection { post :sort }

      member { get :presentation }

      resources :resources, except: [:index, :show] do
        member do
          put 'like',    to: 'resources#upvote'
          put 'dislike', to: 'resources#downvote'
        end
      end

      resources :projects, shallow: true, except: [:index] do
        resources :project_completions, path: '/showcases', except: [:index] do
          member { get :screenshot }
          member { put :approve }
        end
      end
    end
  end

  resources :project_completions, path: '/showcases', only: [:index]

  resources :enrollments, only: [:index]

  get 'users/profile', as: :user_profile

  get 'stackoverflow/tags', as: :stackoverflow_tags

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  load_and_authorize_resource

  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    authorize! :create, Course
    @courses = current_user.created_courses.includes(:creator, :skills).order(:title)
  end

  def show
    @skills = @course.skills.includes(:creator, :primary_language).order(:position)
    if user_signed_in?
      @completed_skills = @skills.includes(:projects).select do |skill|
        skill.projects.any? do |project|
          ( completion = project.completions.find_by(user_id: current_user.id) ) ? completion.completed? : false
        end
      end
      @approved_skills = @completed_skills.select do |skill|
        skill.projects.any? do |project|
          project.completions.find_by(user_id: current_user.id).approved?
        end
      end
    end
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new course_params.merge(creator_id: current_user.id)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
      else
        format.html { render :new }
      end
    end

  rescue ActiveRecord::RecordInvalid => e
    flash[:error] = e.message
    render :new
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
      else
        format.html { render :edit }
      end
    end

  rescue ActiveRecord::RecordInvalid => e
    flash[:error] = e.message
    render :edit
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully deleted.' }
    end
  end

  def sort
    @courses = Course.where(id: params[:course])
    authorize! :sort, *@courses
    @courses.each do |course|
      course.update_attribute( :position, params[:course].index(course.id.to_s) + 1 )
    end
    render nothing: true
  end

private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :abbrev, prereq_ids: [])
  end
end

app/views/courses/_form.html.slim
= simple_form_for @course do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :abbrev, label: 'Abbreviation'
    - other_courses = Course.where.not(id: f.object.id)
    - if other_courses.any?
      = f.association :prereqs, collection: other_courses, label: 'Prerequisites'

  .form-actions
    = f.button :submit

app/views/courses/_table.html.slim
- if courses.any?

  table#courses_table.table.table-striped
    tbody data-update-url=sort_courses_path class="#{'sortable' if can?(:sort, *courses)}"
      - courses.each_with_index do |course, index|
        = content_tag_for :tr, course do
          td= index+1
          td.full= link_to course.title, course
          - if can? :update, course
            td= link_to 'Edit', edit_course_path(course)
          - if can? :destroy, course
            td= link_to 'Delete', course, data: {confirm: "Are you sure you want to permanently delete the \"#{course.title}\" course?"}, method: :delete, class: 'text-danger'

- else

  p No courses found.

app/views/courses/edit.html.slim
h1 Editing course

== render 'form'

app/views/courses/index.html.slim
- breadcrumb :creator_courses

h3
  ' All Courses
  - if can? :create, Course
    = link_to new_course_path do
      .glyphicon.glyphicon-plus-sign

== render 'table', courses: @courses

app/views/courses/new.html.slim
h1 New course

== render 'form'

app/views/courses/show.html.slim
- breadcrumb :course, @course

.alert.alert-info
  ' If you find a great resource for a skill in this course, you can save it via this bookmarklet (drag to the Bookmarks Bar to save it):
  => link_to "javascript:(function(){window.location.assign('#{new_resource_url}?course_id=#{@course.id}&title='+encodeURIComponent(document.title)+'&url='+encodeURIComponent(window.location));})();", class: 'btn btn-xs btn-primary' do
    .glyphicon.glyphicon-plus-sign>
    | Save #{@course.abbrev} Resource

h3
  ' Skills
  - if can? :create, Skill
    = link_to new_course_skill_path(@course) do
      .glyphicon.glyphicon-plus-sign

== render 'skills/table', skills: @skills
== render 'shared/dag', model_name: 'skill'